name: react-flowchart

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3

      - name: Push üì¶
        env:
          EMAIL: 944268618@qq.com
          USERNAME: rick zhou
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd projects/@rick-flow

          echo $EMAIL
          echo $USERNAME

          git init
          git config --global user.email $EMAIL
          git config --global user.name $USERNAME
          git remote add origin https://$ACCESS_TOKEN@github.com/rick-chou/react-flowchart.git

          curl -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" https://api.github.com/user

          git checkout -b main
          git add .
          git commit -m "üåà @rickzhou/flowchart"
          git push -f --set-upstream origin main
